version: '3'


x-filter_by_price: &filter_by_price
  image: tp1-worker
  command: filter_by_price
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=2

x-general_avg_price: &general_avg_price
  image: tp1-worker
  command: general_avg_price
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=2

x-aggregate_by_route: &aggregate_by_route
  image: tp1-worker
  command: aggregate_by_route
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=2

x-dist_calculator: &dist_calculator
  image: tp1-worker
  command: dist_calculator
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=2

x-filter_by_stops: &filter_by_stops
  image: tp1-worker
  command: filter_by_stops
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=2

x-base_filter: &base_filter
  image: tp1-worker
  command: base_filter
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=4


services:
  middleware:
    container_name: middleware
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "15672:15672"
      - "5672:5672"

  server:
    container_name: server
    image: tp1-server
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - package=server
        - include=middleware
    ports:
      - "9000:9000"
    volumes:
      - ../tp1/lib/src:/tp1/lib/src
      - ../tp1/middleware/src:/tp1/middleware/src
      - ../tp1/server/src:/tp1/server/src
    depends_on:
      - middleware

  ## singleton workers

  fastest_by_route:
    image: tp1-worker
    container_name: fastest_by_route
    command: fastest_by_route
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - include=middleware
        - package=worker
    volumes:
      - ../tp1/lib/src:/tp1/lib/src
      - ../tp1/middleware/src:/tp1/middleware/src
      - ../tp1/worker/src:/tp1/worker/src
    environment:
      - REPLICAS=1

  price_by_route:
    image: tp1-worker
    container_name: price_by_route
    command: price_by_route
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - include=middleware
        - package=worker
    volumes:
      - ../tp1/lib/src:/tp1/lib/src
      - ../tp1/middleware/src:/tp1/middleware/src
      - ../tp1/worker/src:/tp1/worker/src
    environment:
      - REPLICAS=1

  ## non-singleton workers

  
  filter_by_price-1:
    <<: *filter_by_price
    container_name: "filter_by_price-1"
  filter_by_price-2:
    <<: *filter_by_price
    container_name: "filter_by_price-2"
  
  general_avg_price-1:
    <<: *general_avg_price
    container_name: "general_avg_price-1"
  general_avg_price-2:
    <<: *general_avg_price
    container_name: "general_avg_price-2"
  
  aggregate_by_route-1:
    <<: *aggregate_by_route
    container_name: "aggregate_by_route-1"
  aggregate_by_route-2:
    <<: *aggregate_by_route
    container_name: "aggregate_by_route-2"
  
  dist_calculator-1:
    <<: *dist_calculator
    container_name: "dist_calculator-1"
  dist_calculator-2:
    <<: *dist_calculator
    container_name: "dist_calculator-2"
  
  filter_by_stops-1:
    <<: *filter_by_stops
    container_name: "filter_by_stops-1"
  filter_by_stops-2:
    <<: *filter_by_stops
    container_name: "filter_by_stops-2"
  
  base_filter-1:
    <<: *base_filter
    container_name: "base_filter-1"
  base_filter-2:
    <<: *base_filter
    container_name: "base_filter-2"
  base_filter-3:
    <<: *base_filter
    container_name: "base_filter-3"
  base_filter-4:
    <<: *base_filter
    container_name: "base_filter-4"
  