version: '3'


x-base_filter: &base_filter
  image: tp1-worker
  command: base_filter
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=1

x-filter_by_price: &filter_by_price
  image: tp1-worker
  command: filter_by_price
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=1

x-filter_by_stops: &filter_by_stops
  image: tp1-worker
  command: filter_by_stops
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=1

x-general_avg_price: &general_avg_price
  image: tp1-worker
  command: general_avg_price
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=1

x-partial_route_agg: &partial_route_agg
  image: tp1-worker
  command: partial_route_agg
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=1

x-price_by_route: &price_by_route
  image: tp1-worker
  command: price_by_route
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=1

x-dist_calculator: &dist_calculator
  image: tp1-worker
  command: dist_calculator
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=1

x-fastest_by_route: &fastest_by_route
  image: tp1-worker
  command: fastest_by_route
  build:
    context: ..
    dockerfile: docker/Dockerfile
    args:
      - include=middleware
      - package=worker
  volumes:
    - ../tp1/lib/src:/tp1/lib/src
    - ../tp1/middleware/src:/tp1/middleware/src
    - ../tp1/worker/src:/tp1/worker/src
  environment:
    - REPLICAS=1


services:
  middleware:
    container_name: middleware
    image: rabbitmq:3-management
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "15672:15672"
      - "5672:5672"

  server:
    container_name: server
    image: tp1-server
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - package=server
        - include=middleware
    ports:
      - "9000:9000"
    volumes:
      - ../tp1/lib/src:/tp1/lib/src
      - ../tp1/middleware/src:/tp1/middleware/src
      - ../tp1/server/src:/tp1/server/src
    depends_on:
      - middleware

  
  base_filter-1:
    <<: *base_filter
    container_name: "base_filter-1"
  
  filter_by_price-1:
    <<: *filter_by_price
    container_name: "filter_by_price-1"
  
  filter_by_stops-1:
    <<: *filter_by_stops
    container_name: "filter_by_stops-1"
  
  general_avg_price-1:
    <<: *general_avg_price
    container_name: "general_avg_price-1"
  
  partial_route_agg-1:
    <<: *partial_route_agg
    container_name: "partial_route_agg-1"
  
  price_by_route-1:
    <<: *price_by_route
    container_name: "price_by_route-1"
  
  dist_calculator-1:
    <<: *dist_calculator
    container_name: "dist_calculator-1"
  
  fastest_by_route-1:
    <<: *fastest_by_route
    container_name: "fastest_by_route-1"
  